# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡


  Thank you and congrats🎉for opening your very first issue in this project. Please adhere to our [Contributing Guidelines](https://github.com/roboTutorLLC/RoboTutor_2020/blob/develop/DEVDOCS.md).🙌
  You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/roboTutorLLC/RoboTutor_2020/blob/develop/.github/pull_request_template.md).
  If you want to report a bug🐞 please follow our [Issue Template](https://github.com/roboTutorLLC/roboTutorLLC/tree/develop/.github/ISSUE_TEMPLATE). Also make sure you include steps to reproduce it and be patient while we get back to you.😄


  Feel free to join our [Discord Community](https://discord.gg/ZHDd59yE).💖 We have different channels for active discussions.✨ Hope you have a great time there!😄

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖


  Thank you and congrats🎉 for opening your first pull request ✨.
  Make sure to adhere to our [Contributing Guidelines](https://github.com/roboTutorLLC/RoboTutor_2020/blob/develop/DEVDOCS.md).🙌 We will get back to you as soon as we can 😄.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀.
